src/cn/com/mjsoft/cms/member/bean/MemberLoginUser.java
package cn.com.mjsoft.cms.member.bean;

import java.util.Collections;
import java.util.List;

import cn.com.mjsoft.cms.common.Constant;
import cn.com.mjsoft.framework.security.Role;
import cn.com.mjsoft.framework.security.headstream.IUser;

public class MemberLoginUser implements IUser
{
 
    private static final long serialVersionUID = 3696971492370505790L;

    private Long userId = Long.valueOf( -1 );

    private String orgCode;

    private Long orgId;

    private String name;

    private String password;

    private Integer status;

    private List roleIdList = Collections.EMPTY_LIST;

    private Role[] ra = null;

    public Object getIdentity()
    {
        return userId;
    }

    public String getUserName()
    {
        return name;
    }

    public void setPassword( String password )
    {
        this.password = password;
    }

    public String getPassword()
    {
        return this.password;
    }

    public Role[] getRoleArray()
    {
        if( this.roleIdList != null && ra == null )
        {
            ra = ( Role[] ) this.roleIdList.toArray( new Role[] {} );
        }

        return ra;
    }

    public List getRoleList()
    {
        return roleIdList;
    }

    public boolean isEnabled()
    {
        return Constant.COMMON.ON.equals( status );
    }

    public boolean isExpired()
    {

        return false;
    }

    public boolean isLocked()
    {

        return false;
    }

    public boolean isPasswordExpired()
    {

        return false;
    }

    public void setName( String name )
    {
        this.name = name;
    }

    public void setUserId( Long userId )
    {
        this.userId = userId;
    }

    public void setRoleIdList( List roleIdList )
    {
        this.roleIdList = roleIdList;
    }

    public Object getOrgIdentity()
    {
        return this.orgId;
    }

    public Object getOrgCode()
    {
        return orgCode;
    }

    public void setOrgCode( String orgCode )
    {
        this.orgCode = orgCode;
    }

    public Object getOrgId()
    {
        return orgId;
    }

    public void setOrgId( Long orgId )
    {
        this.orgId = orgId;
    }

    public Integer getStatus()
    {
        return status;
    }

    public void setStatus( Integer status )
    {
        this.status = status;
    }

    public Role[] getMemberRoleArray()
    {

        return null;
    }

}

WebContent/core/console/LeftTop.jsp
<%@ page contentType="text/html; charset=utf-8" session="false"%>
<%@ taglib uri="/cmsTag" prefix="cms"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />

		<title>menu</title>
		<link href="../style/blue/css/reset-min.css" rel="stylesheet" type="text/css" />
		<link href="../style/blue/images/left.css" rel="stylesheet" type="text/css" />
		<link type="text/css" rel="stylesheet" href="../javascript/tree/xtree2b/css/xtree2.links.css"/>
		<script type="text/javascript" src="../common/js/jquery-1.6.2.min.js"></script>
		<script type="text/javascript" src="../javascript/tree/xtree2b/js/xtree2.js"></script>

		<script>
	 	//去掉点击链接 虚线边框
        window.onload=function()
        {
     		for(var i=0; i<document.links.length; i++)
     		document.links[i].onclick=function(){this.blur()}
        }
	  
		
      </script>


		<style type="text/css">
	  	body{ padding:0px;}
	  </style>

	</head>

	<body class="menutree">

		<table width="100%" height="100%" align="left" border='0' cellspacing='0' cellpadding='0'>
			<tr>
				<td>
					<div>
						<table width="100%" border="0" cellspacing="1" cellpadding="1" class="left_tab">
							<tr>
								<td valign="middle">
									<a id="c1" class="a1" onmouseover="javascript:outCheck(1);" onmouseout="javascript:outCheck(1);" onclick="javascript:gotoContentInfo()"><img src="<cms:Domain/>core/style/icon/report.png" width="16" height="16" title="栏目内容管理" /> </a>
								</td>
								<td>
									<a id="c2" class="a1" onmouseover="javascript:outCheck(2);" onmouseout="javascript:outCheck(2);" onclick="javascript:gotoSpecialInfo()"><img src="<cms:Domain/>core/style/icon/folder_table.png" width="16" height="16" title="专题管理" /> </a>
								</td>
								<td>
									<a id="c3" class="a1" onmouseover="javascript:outCheck(3);" onmouseout="javascript:outCheck(3);" href="javascript:gotoCommendType();"><img src="<cms:Domain/>core/style/icon/database_table.png" width="16" height="16" title="推荐位管理" /> </a>
								</td>
								
								<td>
									<a id="c5" class="a1" onmouseover="javascript:outCheck(5);"  onmouseout="javascript:outCheck(5);"  href="javascript:gotoMessage();"><img src="<cms:Domain/>core/style/icons/document-search-result.png" width="16" height="16" title="全站内容快速管理 " /> </a>
								</td>
								
								<td>
									<a id="c4" class="a1" onmouseover="javascript:outCheck(4);" onmouseout="javascript:outCheck(4);" href="javascript:gotoManageTrashContent();"><img src="<cms:Domain/>core/style/icon/trash2.png" width="16" height="16" title="回收站" /> </a>
								</td>
	
								
								<%--<td>
									<a id="c6" class="a1" onmouseover="javascript:outCheck(6);" onmouseout="javascript:outCheck(6);" href="javascript:gotoWorkbench();"><img src="<cms:Domain/>core/style/icon/application-task.png" width="16" height="16" title="我的工作台" /> </a>
								</td>
							--%></tr>
						</table>
						<div style="height:2px;"></div>
					</div>
				</td>
			</tr>
		</table>
	</body>
</html>

<script>
	 	
	 	
	 	
	  	var c1In = false;
	  	var c2In = false;
	  	var c3In = false;
	  	var c4In = false;
	  	var c5In = false;
	  	var c6In = false;
	  	
	  	//init
	  	$('#c1').attr('class','a3');
			
		$('#c2').attr('class','a1');
		$('#c3').attr('class','a1');
		$('#c4').attr('class','a1');
		$('#c5').attr('class','a1');
		$('#c6').attr('class','a1');
			
		c1In = true;		
			
			
	  	
		function gotoContentInfo()
		{
			window.parent.document.getElementById('lcFrame').src="<cms:Domain/>core/console/ListClass.jsp";
			
			$('#c1').attr('class','a3');
			
			$('#c2').attr('class','a1');
			$('#c3').attr('class','a1');
			$('#c4').attr('class','a1');
			$('#c5').attr('class','a1');
			$('#c6').attr('class','a1');
			
			c1In = true;
			
			c2In = false;
			c3In = false;
			c4In = false;
			c5In = false;
			c6In = false;
			
		}
		
		function gotoSpecialInfo()
		{
			window.parent.document.getElementById('lcFrame').src="<cms:Domain/>core/console/ListSpecialClass.jsp";
			
			$('#c2').attr('class','a3');
			
			$('#c1').attr('class','a1');
			$('#c3').attr('class','a1');
			$('#c4').attr('class','a1');
			$('#c5').attr('class','a1');
			$('#c6').attr('class','a1');
			
			c2In = true;
			
			c1In = false;
			c3In = false;
			c4In = false;
			c5In = false;
			c6In = false;
		}
		
		function gotoCommendType()
		{
			window.parent.document.getElementById('lcFrame').src="<cms:Domain/>core/console/ListCommentType.jsp";
			
			$('#c3').attr('class','a3');
			
			$('#c1').attr('class','a1');
			$('#c2').attr('class','a1');
			$('#c4').attr('class','a1');
			$('#c5').attr('class','a1');
			$('#c6').attr('class','a1');
			
			c3In = true;
			
			c2In = false;
			c1In = false;
			c4In = false;
			c5In = false;
			c6In = false;
		}
		
		function gotoManageTrashContent()
		{
			window.parent.document.getElementById('lcFrame').src="<cms:Domain/>core/console/ListTrashClass.jsp";
			
			$('#c4').attr('class','a3');
			
			$('#c1').attr('class','a1');
			$('#c2').attr('class','a1');
			$('#c3').attr('class','a1');
			$('#c5').attr('class','a1');
			$('#c6').attr('class','a1');
			
			c4In = true;
			
			c2In = false;
			c3In = false;
			c1In = false;
			c5In = false;
			c6In = false;
		}
		
		
		function gotoMessage()
		{
			window.parent.parent.document.getElementById('main').src="<cms:Domain/>core/content/QuickManageContent.jsp";
			
			$('#c5').attr('class','a3');
			
			$('#c1').attr('class','a1');
			$('#c2').attr('class','a1');
			$('#c4').attr('class','a1');
			$('#c3').attr('class','a1');
			$('#c6').attr('class','a1');
			
			c5In = true;
			
			c2In = false;
			c3In = false;
			c4In = false;
			c1In = false;
			c6In = false;
		}
		
		function gotoWorkbench()
		{
			window.parent.parent.document.getElementById('main').src="<cms:Domain/>core/console/Workbench.jsp?isReply=0";
			
			$('#c6').attr('class','a3');
			
			$('#c1').attr('class','a1');
			$('#c2').attr('class','a1');
			$('#c4').attr('class','a1');
			$('#c5').attr('class','a1');
			$('#c3').attr('class','a1');
			
			c6In = true;
			
			c2In = false;
			c3In = false;
			c4In = false;
			c5In = false;
			c1In = false;
		}
		
		function outCheck(flag)
		{		
			var currentClass = $('#c'+flag+'').attr('class');
			
			var testFlag = 0;
			
			if(c1In)
			{
				testFlag =1;
			}
			if(c2In)
			{
				testFlag =2;
			}
			if(c3In)
			{
				testFlag =3;
			}
			if(c4In)
			{
				testFlag =4;
			}
			if(c5In)
			{
				testFlag =5;
			}
			if(c6In)
			{
				testFlag =6;
			}
			
			
			
			
			//没选中
			if(testFlag !=flag )
			{
				if(currentClass == 'a1')
				{
					$('#c'+flag+'').attr('class','a2');
				}
				else
				{
					$('#c'+flag+'').attr('class','a1');
				}
			}

			
		}

		
		
		
		
      </script>

WebContent/core/console/ListClassFramePage.jsp
<%@ page contentType="text/html; charset=utf-8" session="false"%>
<%@ taglib uri="/cmsTag" prefix="cms"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title></title>
		<link href="../style/blue/css/frame.css" rel="stylesheet" type="text/css" />



		<script language="javascript">  




  </script>
		<style>
html, body {
	margin:0;
	padding:0;
	height:100%;
}

</style>

	</head>
	<frameset rows="32,*" border="0" frameborder="no" framespacing="0" frameborder="0" scrolling="no" noresize="noresize" name="listClassFrame" id="listClassFrame">
		<frame src="LeftTop.jsp" id="lefttopFrame" name="lefttopFrame" framespacing="0" frameborder="0" scrolling="no" noresize="noresize"  />
		<frame src="ListClass.jsp" id="lcFrame" name="lcFrame" framespacing="0" frameborder="0" scrolling="auto" noresize="noresize"  />
	</frameset>
	<noframes>
		<body>
		</body>
	</noframes>
</html>

WebContent/core/console/ListCommendTypeFramePage.jsp
<%@ page contentType="text/html; charset=utf-8" session="false"%>
<%@ taglib uri="/cmsTag" prefix="cms"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title></title>
		<link href="../style/blue/css/frame.css" rel="stylesheet" type="text/css" />



		<script language="javascript">  




  </script>
		<style>
html, body {
	margin:0;
	padding:0;
	height:100%;
}

</style>

	</head>
	<frameset rows="32,*" border="0" frameborder="no" framespacing="0" frameborder="0" scrolling="no" noresize="noresize" name="listClassFrame" id="listClassFrame">
		<frame src="LeftTop.jsp" name="lefttopFrame" framespacing="0" frameborder="0" scrolling="no" noresize="noresize" id="topFrame" />
		<frame src="ListCommentType.jsp" name="lcFrame" framespacing="0" frameborder="0" scrolling="auto" noresize="noresize" id="topFrame" />
		
	</frameset>
	<noframes>
		<body>
		</body>
	</noframes>
</html>

WebContent/core/console/ListCommentType.jsp
<%@ page contentType="text/html; charset=utf-8" session="false"%>
<%@ taglib uri="/cmsTag" prefix="cms"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />


		<title>menu</title>
		<link href="../style/blue/css/reset-min.css" rel="stylesheet" type="text/css" />
		<link href="../style/blue/images/left.css" rel="stylesheet" type="text/css" />
		<link type="text/css" rel="stylesheet" href="../javascript/tree/xtree2b/css/xtree2.links.css"></link>

		<script type="text/javascript" src="../common/js/jquery-1.6.2.min.js"></script>

		<script type="text/javascript" src="../javascript/tree/xtree2b/js/xtree2.js"></script>


		<script>
	 	//去掉点击链接 虚线边框
        window.onload=function()
        {
     		for(var i=0; i<document.links.length; i++)
     		document.links[i].onclick=function(){this.blur()}
        }
        
        function loadChildTree() {
        //必须放置一个空方法
        }
	 
      </script>


		<style type="text/css">
html{
scrollbar-3dlight-color:#fff; /*- 最外左 -*/  
scrollbar-highlight-color:#fff; /*- 左二 -*/  
scrollbar-face-color:#DCE7F5; /*- 面子 -*/  
scrollbar-arrow-color:#407DCA; /*- 箭头 -*/  
scrollbar-shadow-color:#efefef; /*- 右二 -*/  
scrollbar-darkshadow-color:#E9EDF8; /*- 右一 -*/  
scrollbar-base-color:#D7DCE0; /*- 基色 -*/  
scrollbar-track-color:#fcfcfc;/*- 滑道 -*/  
 

	}
	body{ padding:0px;
	margin-left: 4px;
	}
</style>

	</head>

	<body class="menutree">

		<table width="100%" height="100%" align="left" border='0' cellspacing='0' cellpadding='0'>
			<tr>
				<td>
					<div>
					
						
					
						<cms:CurrentSite>
							<script type="text/javascript">
			basepath="<cms:Domain/>";
				///////////////////ajax ////////

			var targetJSONsrc = '../../channel/listCommendTypeInfoTree.do';
			//var targetListContentSrc =item.targetListPage+'?classId=';
			
			var parentId = -9999;//暂时没有分站，永远为总站-9999
			var tree = new WebFXTree('${CurrSite.siteName}推荐位');
			
			tree.icon = "images/monitor.png";
			tree.openIcon="images/monitor.png";
			tree.setId(-9999);
			tree.target= 'main';
			tree.setAction("javascript:");
			tree.thisNodeLoadComplete=true;
			
			current = tree;
		 
			var currentClass;
			
			var classId = '';
			
			
			$.ajax({
		  		type: "POST",
		   		 url: targetJSONsrc,
		   		data: 'parentClassId='+parentId,
		
		       	success: function(msg)
		        {     
		       				var jsonObj = eval("("+msg+")");
		           			var x;
			      			
			      			var xc;
			      			
			      			$.each
			      			(
			      				jsonObj,
			      				function(i,item)
			      				{  
			      				
			      					if(item.rootClassId == '-1')
			      					{
			      						x = new WebFXTreeItem(item.rootClassName);
				      					x.setId('root'+i);
				      					
				      					x.openIcon="../../core/style/icons/folder-open.png";
				      					x.icon="../../core/style/icons/folder.png";
				      					

				      					x.expand();
				      					
				      					currentClass = x;
				      					
				      					current.add(x);
			      					
			      					}
			      					else
			      					{
				      					x = new WebFXTreeItem(item.commendName);
				      					x.setId("comm:"+item.commendTypeId);
				      					
				      					//如果为通用推荐位,则取站点第一个classId
				      					if(item.classId == '-9999')
				      					{
				      						classId = item.firstClassId;
				      					}
				      					else
				      					{
				      						classId = item.classId;
				      					}
				      					
				      					x.setAction('<cms:Domain/>core/content/ManageCommendContent.jsp?typeId='+item.commendTypeId+'&classId='+classId);
				      					x.target= 'main';
				      					
				      					
				      					
				      					//如果不是叶子节点，需要为他创建一个loading节点
				      					
				      					
				      						
				      						x.openIcon="../../core/style/icons/document-text-image.png";
				      						x.icon="../../core/style/icons/document-text-image.png";
				      						
				      						currentClass.add(x);
			      					}
			      					
			      					
			      				
			      				}	      			
			      			);
			      			
			      			     			
			      		 
		        }
		 	});	
			
			
			 
			tree.write();
			
			tree.expand();
			
			
			

function manageCommendInfo()
{
	window.parent.parent.document.getElementById('main').src="<cms:Domain/>core/content/ManageCommendContent.jsp";
 
}

function manageBlockInfo()
{
	window.parent.parent.document.getElementById('main').src="<cms:Domain/>core/block/ManageBlockPushContent.jsp";
}



			
		</script>
						</cms:CurrentSite>
						<br />
						<br />
						<br />




























					</div>
				</td>
			</tr>
		</table>
	</body>
</html>

WebContent/core/console/main.jsp
<%@ page contentType="text/html; charset=utf-8" session="false"%>
<%@ taglib uri="/cmsTag" prefix="cms"%>
<%@ page contentType="text/html; charset=utf-8"%>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN">
<html>
	<head>
		<%
			response.setHeader("Pragma", "No-cache");
			response.setHeader("Cache-Control", "no-cache");
			response.setDateHeader("Expires", 0);
		%>

		<title>合肥明靖信息科技JTopCMS</title>
		<link rel="stylesheet" type="text/css" href="../../style/default/console.css" />

	</head>
	<script>



</script>
	<frameset rows="80,*" border="0" frameborder="yes" framespacing="0" name="mainframe" id="mainframe">
		<frame src="top_2.jsp" name="topFrame" framespacing="0" frameborder="0" scrolling="no" noresize="noresize" id="topFrame" />
		<frameset row="*" cols="152,9,*" framespacing="0" frameborder="0" scrolling="no" noresize="noresize" name="centerFrame" id="centerFrame">
			<frame src="<cms:BasePath/>core/console/ListLeft.jsp" name="leftFrame" frameborder="0" scrolling="no" id="leftFrame" />
			<frame src="mid.jsp" name="midFrame" frameborder="0" scrolling="no" id="midFrame" />
			<frame src="welcome.jsp" name="contentFrame" id="contentFrame" />
		</frameset>
	</frameset>
	<noframes>
		<body>
		</body>
	</noframes>
</html>

WebContent/core/console/top.jsp
<%@ page contentType="text/html; charset=utf-8" session="false"%>
<%@ taglib uri="/cmsTag" prefix="cms"%>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
	<head>
		<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
		<meta http-equiv="content-type" content="text/html; charset=utf-8" />
		<title></title>
		<link href="../style/blue/css/reset-min.css" rel="stylesheet" type="text/css" />
		<link href="../style/blue/css/default.css" type="text/css" rel="stylesheet" />
		<script type="text/javascript" src="../common/js/jquery-1.7.gzjs"></script>
		<script type="text/javascript" src="../javascript/commonUtil_src.js"></script>
		<script type="text/javascript" src="../javascript/dialog/lhgdialog.min.js?skin=iblue"></script>

		<script type="text/javascript">
		var currentTabId = '';		
		
		var defaultTarget="/core/console/menu.jsp";
		
		
		function initFirstTargetResource(target,resId)
		{   
	
		  target=defaultTarget;	
		  
		  var targetFrame = window.parent.document.getElementById("leftMenu");
		 
		  targetFrame.src="<cms:Domain/>"+target+"?parResId="+resId+"&random="+Math.random();   
		}
		
		</script>

	</head>

	<cms:LoginUser>
		<body>
			<cms:CurrentSite>
				<table width="100%" class="top">
					<tr>
						<td id="toppage" align="right" valign="top"  >
						<script>
						$('#toppage').attr('style','width:'+(window.screen.width * 0.155-9)+'px')
						</script>
						
							<div class="logo">
								<span class="height53">Version 3.0 &nbsp;开源版&nbsp;(MySQL)</span>
							</div>
						</td>
						<td align="left">
							<div class="topinfor">
								<div class="Black10"></div>
								当前管理员:
								<span> ${Auth.apellation}</span>， 您当前登录在

								<select id="currentSite" onchange="javascript:changeCurrentSite();" class="form-select">
									<cms:Site>
										<option value="${Site.siteId}">
											${Site.siteName}&nbsp;&nbsp;
										</option>
									</cms:Site>
									<cms:Empty flag="Site">
										<option value="-9999">
											--- 无站点信息 ---&nbsp;&nbsp;
										</option>
									</cms:Empty>
								</select>

								<script>
							
							 initSelect('currentSite','${CurrSite.siteId}');
								
						</script>

							</div>
							<div class="nav">
								<ul>
									<cms:SecurityResourceList parentId="-1" type="1">
										<cms:SecurityResource >

											<cms:if test="${status.index == 0}">

												<li>
													<a class="curr" id="mainTab${Resource.secResId}" href="javascript:void(0)" onmousedown="javascript:dierctTargetResource('${Resource.target}','${Resource.secResId}',this);">${Resource.resourceName} </a>
												</li>
												<script>
										currentTabId = "mainTab${Resource.secResId}";
										
										if('/core/console/ListClassFramePage.jsp' != '${Resource.target}')
										{
											 
											initFirstTargetResource('${Resource.target}','${Resource.secResId}');
										}
										else
										{
										 	 if('true' != '${param.notReload}')
										 	 {
											  
											  var targetFrame = window.parent.document.getElementById("leftMenu");
											 
											  targetFrame.src="<cms:BasePath/>core/console/ListClassFramePage.jsp?parResId=${Resource.secResId}&random="+Math.random(); 
											  
											  } 
										}
										
									</script>
											</cms:if>
											<cms:else>

												<li>
													<a id="mainTab${Resource.secResId}" href="javascript:void(0)" onmousedown="javascript:dierctTargetResource('${Resource.target}','${Resource.secResId}',this);">${Resource.resourceName} </a>
												</li>
											</cms:else>

										</cms:SecurityResource>
									</cms:SecurityResourceList>
								</ul>
							</div>
							<div class="header-ico">
								<ul>
									<li>
										<a class="ico-out" href="javascript:loginout();">注销</a>
									</li>
									<li>
										<a class="ico-key-solid" href="javascript:changePassword('${Auth.identity}','${Auth.apellation}');">修改密码</a>
									</li>
									<li>
										<a class="ico-user" href="javascript:editUser('${Auth.identity}','${Auth.apellation}');">个人信息</a>
									</li>
 
									
									<li>
										<a class="ico-wb" href="javascript:gotoWorkbench();">我的工作台</a>
									</li>
									
									<li>
										
										<a href="javascript:openMsgDialog();" style="position:relative;" class="ico-mail">站内信件</a>
										<span id="msgShow" style="font-size:11px" class="mailnum">9+</span>
									</li>
								</ul>
							</div>
						</td>
					 
					</tr>
				</table>


				<!--[if lt IE 7]>
        <script type="text/javascript" src="js/unitpngfix.js"></script>
<![endif]-->
		</body>
</html>
<script type="text/javascript">

function loginout()
{
		 

		 
 	    
	     
		var url = "<cms:BasePath/>login/postLogin.do?action=LoginOut&<cms:Token mode='param'/>";
        
         
     
           
		$.ajax({
				      		type: "POST",
				       		url: url,
				       		data: '',
				   
				       		success: function(mg)
				            {     
				            	var msg = eval("("+mg+")");
				            	
				               if('success' == msg)
				               {
				               		 window.location.href = "<cms:BasePath/>core/SystemManager/login/page.jsp";
				               		
				               }
				                
				              
				            }
		});	

      
     
}

function dierctTargetResource(target,resId,selectTab)
{   

  if(null == target || '' == target.trim())
  {
      target=defaultTarget;
  }
  
  var curTab = document.getElementById(currentTabId);
  if(curTab != null)
  {
  	curTab.className  = '';
  }
  selectTab.className  = 'curr';
  currentTabId= selectTab.id;

  //var targetFrame = window.parent.document.all[id='leftFrame'];
  var targetFrame = window.parent.document.getElementById("leftMenu");
 
  targetFrame.src="<cms:Domain/>"+target+"?parResId="+resId+"&random="+Math.random();   
}



function changeCurrentSite()
{
   var siteId = document.getElementById('currentSite').value;
	
   var url = "<cms:BasePath/>security/changeLoginUserSite.do?siteId="+siteId+"&random="+Math.random();
 
   $.ajax({
   type:'POST',
   async:false,
   url:url,
   success:
  	function(data, textStatus)
  	{
  		 var msg = eval("("+data+")");
  	 	 if('success' == msg)
  	 	 {
  	 	 	window.parent.window.location.reload();
  	 	 }
  	}
  });
  

}

function mainPage()
{
	window.parent.location='<cms:BasePath/>core/console/main_blue.jsp'
}

function goMessagePage()
{
	  var targetFrame = window.parent.document.getElementById("main");

      targetFrame.src="<cms:Domain/>core/message/ManageSiteMessage.jsp";  

}

checkMotReadMessageCount();
setInterval("checkMotReadMessageCount()",20*1000);

function checkMotReadMessageCount()
{
	var url = "<cms:BasePath/>message/getNotReadMsgCount.do";
 					
	$.ajax({
  		type: "POST",
   		url: url,
   		data: '',
		dataType: 'json',
       	success: function(msg)
        {      
           var count = parseInt(msg);
      
           if(count >9)
           {
           		$('#msgShow').html('9+');
           }
           else if(count > 0)
           {  
           		$('#msgShow').show();
           	    $('#msgShow').html(count);
           }
           else
           {
           		$('#msgShow').hide();
           }
           
        }
 	});	

}




function editUser(userId, userName)
{
   $.dialog({ 
	    id : 'oesr',
    	title : '当前登录管理员 - '+userName,
    	width: '620px',  
    	height: '560px', 
    	lock: true, 
        max: false, 
        min: false,
        resize: false,
       
        content: 'url:<cms:Domain/>core/security/EditSystemUser.jsp?userId='+userId

	});
}

function changePassword(userId, userName)
{
	$.dialog({ 
	    id : 'ocpd',
    	title : '修改密码 - '+userName,
    	width: '530px', 
    	height: '185px',  
    	lock: true, 
        max: false, 
        min: false,
        resize: false,
       
        content: 'url:<cms:Domain/>core/security/ChangePassword.jsp?userId='+userId
	});

}


function openMsgDialog()
{
	$.dialog({ 
	    id : 'omsgd',
    	title : '站内消息',
    	width: '1200px', 
    	height: '750px', 
    	lock: true, 
        max: false, 
        min: false,
        resize: false,
       
        content: 'url:<cms:Domain/>core/message/ManageSiteMessageDialog.jsp?dialog=true'
	});

}

function gotoWorkbench()
{
			window.parent.parent.document.getElementById('main').src="<cms:Domain/>core/console/Workbench.jsp?isReply=0";
			
		 
}

   
</script>
</cms:CurrentSite>
</cms:LoginUser>